export type Project = {
  id: string;
  keyStatus: string;
  name: string;
  operasi: string;
  kam: string;
  ktt: string;
  owner: string;
  nilaiOkHps: string;
  statusTender: string;
  sumberDana: string;
  payment: string;
  jenisKontrak: string;
  periode: string; // ISO date or ""
  periodeTender: string;
  pemasukanHarga: string;
  koordinatorQs: string;
  koordinatorStatus: string;
  statusSaatIni: string;
  status: "open" | "closed";
};

export const projects: Project[] = [
  {"id": "1", "keyStatus": "Submit", "name": "Pengendali Banjir Kali Kedurus di Kota Surabaya", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Ganar Ardhiata", "owner": "PU - SDA", "nilaiOkHps": "350", "statusTender": "Pasar Dini", "sumberDana": "Loan World Bank", "payment": "", "jenisKontrak": "", "periode": "2026-01-01", "periodeTender": "Des 2025 - Feb 2026", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "2", "keyStatus": "", "name": "Pembangunan Sabodam Gayo Lues", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "200", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "3", "keyStatus": "", "name": "Irigasi Sei Wampu", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "200", "statusTender": "Pasar Dini", "sumberDana": "APBN", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Konfirmasi ke KAM/KTT untuk update tender\n- Dalam proses design dan anggaran di Owner.\n- Terinfo ada 3 paket, dengan total nilai 1000 T", "status": "open"},
  {"id": "4", "keyStatus": "", "name": "Bendung Sidoras", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "", "statusTender": "Pasar Dini", "sumberDana": "APBN", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Konfirmasi ke KAM/KTT untuk update tender", "status": "open"},
  {"id": "5", "keyStatus": "Terkontrak", "name": "Penanganan Pasca Bencana Muara Sungai", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Rizwan Yan Tanzil", "owner": "PU - SDA", "nilaiOkHps": "200", "statusTender": "Budgetary", "sumberDana": "APBN", "payment": "", "jenisKontrak": "", "periode": "2026-03-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Sudah RKP", "status": "open"},
  {"id": "6", "keyStatus": "", "name": "Pengendali Banjir Kawasan Industri Medan (KIM)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Aris Munandar", "owner": "PU - SDA", "nilaiOkHps": "250", "statusTender": "Pasar Dini", "sumberDana": "World Bank", "payment": "", "jenisKontrak": "", "periode": "2026-03-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "7", "keyStatus": "", "name": "Peningkatan Jaringan Irigasi Tahap IV (Oplah) Jambi", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "50", "statusTender": "Pasar Dini", "sumberDana": "APBN", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "8", "keyStatus": "", "name": "Pengendalian Banjir Sistem Sungai Bendung Kota Palembang", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Reza Apriadi", "owner": "PU - SDA", "nilaiOkHps": "424,00", "statusTender": "Pasar Dini", "sumberDana": "World Bank", "payment": "Monthly", "jenisKontrak": "Unit price", "periode": "2026-03-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Konfirmasi ke KAM/KTT untuk update tender\n- SIRUP sudah tayang 15 Okt 2025\n- Rencana tender di Desember 2025\n- JO leader ADHI-WK-BRP", "status": "open"},
  {"id": "9", "keyStatus": "", "name": "Pembangunan Jaringan Air Baku KSCS Paket 4", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - CK", "nilaiOkHps": "180", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "10", "keyStatus": "", "name": "Pengendali Banjir Sungai Ciliwung Paket 1 (Manggarai - Kamp. Melayu)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "238", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran", "status": "open"},
  {"id": "11", "keyStatus": "", "name": "Pengendali Banjir Sungai Ciliwung Paket 2 (Kamp. Melayu - Kalibata)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "180", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran", "status": "open"},
  {"id": "12", "keyStatus": "", "name": "Pengendali Banjir Sungai Ciliwung Paket 3 (Kalibata - Condet)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "210", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran", "status": "open"},
  {"id": "13", "keyStatus": "", "name": "Pengendali Banjir Sungai Ciliwung Paket 4 (Condet - TB Simatupang)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "190", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran", "status": "open"},
  {"id": "14", "keyStatus": "", "name": "Kali Bekasi Paket 2", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "760", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran", "status": "open"},
  {"id": "15", "keyStatus": "", "name": "Kali Bekasi Paket 3", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "757", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran", "status": "open"},
  {"id": "16", "keyStatus": "", "name": "Kali Bekasi Paket 4", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "797", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran", "status": "open"},
  {"id": "17", "keyStatus": "", "name": "Kali Bekasi Paket 5", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "792", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran", "status": "open"},
  {"id": "18", "keyStatus": "", "name": "Irigasi Rentang Kanan", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "500", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Pendanaan dari JICA\n- Per tgl 30 Sept 2025 KTT menginfokan masih tahap RPB\n- Rencana tayang 2027", "status": "open"},
  {"id": "19", "keyStatus": "", "name": "Cimanuk Rising Dykes at Upper Cimanuk Garut (CWC-7g)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "271", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran", "status": "open"},
  {"id": "20", "keyStatus": "", "name": "Waste Water Treatment Plan Banjardowo- CWIS 01 (IPAL)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Eko Supriyono", "owner": "PU - CIPTA KARYA", "nilaiOkHps": "670", "statusTender": "Tender Diikuti", "sumberDana": "Loan ADB", "payment": "Termijn min 2%", "jenisKontrak": "Lumpsum D&B", "periode": "2026-01-01", "periodeTender": "Jan-Apr 2026", "pemasukanHarga": "2026-04-06", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "-Pemasukan tgl 9 Maret 2026\n- CCEED - WIKA KSO (51 : 49) (BATAL). KSO menjadi EPEPL-WIKA-PJL", "status": "open"},
  {"id": "21", "keyStatus": "", "name": "Commercial area sewerline (central and south ) semarang - CWIS - 04", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Deddy Anwar", "owner": "PU - CIPTA KARYA", "nilaiOkHps": "244.871", "statusTender": "Pasar Dini", "sumberDana": "Loan ADB", "payment": "Termijn min 2%", "jenisKontrak": "Unit price", "periode": "2026-04-01", "periodeTender": "Mar - Apr 2026", "pemasukanHarga": "2026-04-24", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "-Info KAM akan menjadi leader KSO WIKA - JAKON\n'- Proses NR2\n- Proses Dok Tender dan Jaminan", "status": "open"},
  {"id": "22", "keyStatus": "", "name": "Normalisasi Sungai Sayung", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "350", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Konfirmasi ke SVP/GM untuk KTT\n- Konfirmasi ke KAM/KTT untuk update tender", "status": "open"},
  {"id": "23", "keyStatus": "", "name": "Juana River Improvement", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "326", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran, klo bisa ga usah ikut", "status": "open"},
  {"id": "24", "keyStatus": "", "name": "Normalisasi JU-1 River (Kudus)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "220", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM bukan sasaran", "status": "open"},
  {"id": "25", "keyStatus": "", "name": "Normalisasi Pompa Kali Baru Kali Asin", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "350", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info dari DGM pak Visi", "status": "open"},
  {"id": "26", "keyStatus": "", "name": "Sungai Silandak", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "180", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info dari DGM pak Visi", "status": "open"},
  {"id": "27", "keyStatus": "", "name": "Babakan River & Drainage Works in Brebes (CWC-5b)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "270", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM sasaran", "status": "open"},
  {"id": "28", "keyStatus": "Cancel", "name": "Pengendali Banjir Kawasan Yogyakarta International Airport (YIA)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "216.2", "statusTender": "Tender Diikuti", "sumberDana": "APBN", "payment": "", "jenisKontrak": "", "periode": "2026-02-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Close", "statusSaatIni": "- Info KAM bukan sasaran\n- SIRUP sudah keluar 14 Oktober 2025", "status": "closed"},
  {"id": "29", "keyStatus": "", "name": "Main Trunk Jogja Paket 2 (Limbah)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - CK", "nilaiOkHps": "220", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "30", "keyStatus": "", "name": "Pembangunan Pengendali Banjir Afvour Buntung Kab. Sidoarjo", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "BBWS Brantas", "nilaiOkHps": "250", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Akan tayang di Oktober 2025", "status": "open"},
  {"id": "31", "keyStatus": "Submit", "name": "Pengendali Banjir Kali Lamong", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Ganar Ardhiata", "owner": "BBWS Bengawan Solo Wilayah Sungai Lamong", "nilaiOkHps": "224,49", "statusTender": "Tender Diikuti", "sumberDana": "APBN", "payment": "Termijn Bulanan", "jenisKontrak": "Unit price", "periode": "2026-01-01", "periodeTender": "Jan-Feb 2026", "pemasukanHarga": "2026-02-13", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- HK-WIKA KSO (60:40)", "status": "open"},
  {"id": "32", "keyStatus": "", "name": "Sabo Dam Gunung Semeru Paket S4", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "", "owner": "PU - SDA", "nilaiOkHps": "169", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Ada 2 paket yang besar yang belum rilis, paket kecilnya sudah rilis\n- Nilai 2 paket masing-masing 150 & 170\n- Pendanaan info awal JICA\n- Info KAM akan tayang di 2026\n- Rencana tayang di Nopember 2025", "status": "open"},
  {"id": "33", "keyStatus": "", "name": "Rehabilitasi Irigasi Mrican", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Ery Nugroho", "owner": "PU - SDA", "nilaiOkHps": "368,09", "statusTender": "Tender Diikuti", "sumberDana": "SBSN", "payment": "Termijn Bulanan", "jenisKontrak": "Unit price", "periode": "2026-01-01", "periodeTender": "Jan-Feb 2026", "pemasukanHarga": "2026-02-09", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Pemasukan terakhir 9 Feb 2026\n- Aanwijzing tgl 3 Feb 2026\n- WIKA-JAKON-KARTA (55:30:15)", "status": "open"},
  {"id": "34", "keyStatus": "", "name": "Peningjkatan Jaringan Irigasi D.I Waduk Bening Paket 2", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Dendy P", "owner": "PU - SDA", "nilaiOkHps": "327,61", "statusTender": "Tender Diikuti", "sumberDana": "SBSN", "payment": "Termijn Bulanan", "jenisKontrak": "Unit price", "periode": "2026-01-01", "periodeTender": "Jan-Feb 2026", "pemasukanHarga": "2026-02-09", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Pemasukan terakhir 9 Feb 2026\n- Aanwijzing tgl 3 Feb 2026\n- WIKA-JAKON-KARTA (55:30:15)", "status": "open"},
  {"id": "35", "keyStatus": "", "name": "Rehabilitasi D.I Talang", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Andrianto Widhi Nugroho", "owner": "PU - SDA", "nilaiOkHps": "272,84", "statusTender": "Tender Diikuti", "sumberDana": "SBSN", "payment": "Termijn Bulanan", "jenisKontrak": "Unit price", "periode": "2026-01-01", "periodeTender": "Jan-Feb 2026", "pemasukanHarga": "2026-02-09", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "- Pemasukan terakhir 9 Feb 2026\n- Aanwijzing tgl 3 Feb 2026\n- WIKA-JAKON-KARTA (55:30:15)", "status": "open"},
  {"id": "36", "keyStatus": "", "name": "Perluasan Dermaga Teluk Lamong", "operasi": "Operasi 1", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "Pelindo", "nilaiOkHps": "390", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "-'Info KAM belum RPB", "status": "open"},
  {"id": "37", "keyStatus": "", "name": "Hunian Tetap Pasca Bencana - Aceh Tamiang", "operasi": "Operasi 2", "kam": "Arif K", "ktt": "Kopas B", "owner": "Kemen PKP", "nilaiOkHps": "170", "statusTender": "Pasar Dini", "sumberDana": "APBN", "payment": "Milestone", "jenisKontrak": "Harga Satuan", "periode": "2026-01-01", "periodeTender": "2026-01-01", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "-Pembuatan Paparan awal dan penyiapan harga penawaran di januari 2026\n- Pembuatan Mockup Huntap sudah selesai...menunggu proses SPK", "status": "open"},
  {"id": "38", "keyStatus": "", "name": "Eco Fishing Belawan (Tambak)", "operasi": "Operasi 1", "kam": "Fajar Ariyanto", "ktt": "", "owner": "KKP", "nilaiOkHps": "", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Proyek Sudah berjalan", "status": "open"},
  {"id": "39", "keyStatus": "Terkontrak", "name": "Penanganan Pasca Bencana Jalan Ruas Sibolga", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "Masy'aril", "owner": "PU - Bina Marga", "nilaiOkHps": "250", "statusTender": "Budgetary", "sumberDana": "APBN", "payment": "", "jenisKontrak": "", "periode": "2026-02-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Close", "statusSaatIni": "- sdh pra RKP", "status": "closed"},
  {"id": "40", "keyStatus": "", "name": "Jembatan Muka Kuning - Batam", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "Syahril Budi", "owner": "BP Batam", "nilaiOkHps": "400", "statusTender": "Pasar Dini", "sumberDana": "BP BATAM", "payment": "", "jenisKontrak": "", "periode": "2026-09-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Rencana akan ada review desain dari BP Batam dg Konsultan lama Tri Mantra, ada kemungkinan BP akan cari konsultan lain utk Review lebih lanjut\n- KSO WIKA 60% : 40% MBJ (Maju Bersama Jaya)\n- Sudah dibuatkan grup WA (close)\n- per tanggal 29 Sept terinfo sudah terpilih konsultan, saat ini masih ada organik WIKA yang standby bantu desain dan hitung volume\n'- Update per Maret 2026 Waskita sdh penetrasi masuk ke BP Batam\n'- Update di MR Juli ;  sudah bukan sasaran Wika", "status": "open"},
  {"id": "41", "keyStatus": "", "name": "Jembatan Tratak Buluh (Riau)", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "", "owner": "PU - Bina Marga", "nilaiOkHps": "150", "statusTender": "Pasar Dini - RKAP", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Konfirmasi ke KAM/KTT untuk update dokumen tender\n- Belum ada info lebih lanjut kelanjutan tender/proyek", "status": "open"},
  {"id": "42", "keyStatus": "", "name": "Fly Over Ujan Mas/Gunung Mas - Muara Enim", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "", "owner": "PT. KAI", "nilaiOkHps": "300", "statusTender": "", "sumberDana": "PT. Kereta Api Indonesia", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Akan dikoordinasikan JIKA memang harus dilakukan drone berbarengan dengan FO Sudirman", "status": "open"},
  {"id": "43", "keyStatus": "", "name": "Depo Muara Gula (Muara Enim)", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "PT. KAI", "nilaiOkHps": "1000", "statusTender": "Pasar Dini", "sumberDana": "PT. Kereta Api Indonesia", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Info melalui KAM dan GM Operasi 1", "status": "open"},
  {"id": "44", "keyStatus": "", "name": "Jalan Tol Trans Sumatera / Simpang Susun Mataram (Palembang)", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "", "owner": "HK Toll", "nilaiOkHps": "500", "statusTender": "Pasar Dini - RKAP", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Konfirmasi ke KAM/KTT untuk update dokumen tender\n'- sd 3 Maret 2026 dari KAM blm ada update\n'- info di MR Juli 2026 Updatenya dikerjakan HK sendiri", "status": "open"},
  {"id": "45", "keyStatus": "", "name": "Akses Merak-Tangerang (Alamsutra) / SS Cikupa", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "Adiwangsa / Alam sutera", "nilaiOkHps": "200", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Terkendala Lahan, karena pembebasan oleh Pemda\n- Terinfo tgl 30 sept 2025 dari KTT tender akan digeser ke tahun depan\n'- Tunggu Basik Design review BPJT di Pleno 20 Juli 2026", "status": "open"},
  {"id": "46", "keyStatus": "", "name": "Akses Tol Cibenda", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "BSD", "nilaiOkHps": "300", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Info dari KAM yang pendekatan Pak Ari Mardika dan Pak Andri", "status": "open"},
  {"id": "47", "keyStatus": "Submit", "name": "Tol Serbaraja 2A", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "M. Andri", "owner": "Sinarmas", "nilaiOkHps": "250", "statusTender": "Pasar Dini", "sumberDana": "Swasta Sinarmas", "payment": "Monthly", "jenisKontrak": "Mix", "periode": "2026-02-01", "periodeTender": "2026-02-01", "pemasukanHarga": "2026-02-19", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "-sudah disubmit penawaran tgl 19 Feb 2026\n- jadwal Beauty Contest 6 Maret 2026", "status": "open"},
  {"id": "48", "keyStatus": "", "name": "Penataan area terminal 2F (parkir) lounge umroh Bandara Soeta", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "M. Andri", "owner": "ANGKASA PURA", "nilaiOkHps": "18", "statusTender": "Pasar Dini", "sumberDana": "Injourney", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- sd Maret 2026 dihandle oleh tim proyek Irigasi Belimbing\n'- pagu naik menjadi 26 M (plus ppn) semula 18 M", "status": "open"},
  {"id": "49", "keyStatus": "", "name": "FO Bintaro Puspita", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "Pemprov DKI", "nilaiOkHps": "100", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Belum ada kejelasan pendanaan dan perijinan serta sosialisasi ke warga\n- Sudah muncul di SIRUP", "status": "open"},
  {"id": "50", "keyStatus": "", "name": "Package 2: Construction of Main Trunk Sewer Jakarta Sewerage Development Project (Zone 6) (Phase 1), JICA Loan IP-579 (Retender)", "operasi": "Operasi 1", "kam": "Firman Setyawan", "ktt": "Nur Rahim", "owner": "PU - SDA", "nilaiOkHps": "1300", "statusTender": "Re-tender", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- JO Kumagai Gumi 60% - WIKA ___- Jakon ___ (tbc)\n- Jadwal PQ di May 2026, mengajukan ulang tim tender, diagendakan paparan pasar dini setelah ada dokumen PQ", "status": "open"},
  {"id": "51", "keyStatus": "", "name": "Proyek LRT Jakarta Phase 1C : Manggarai - Dukuh Atas", "operasi": "Operasi 1", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "PT Jakpro", "nilaiOkHps": "1711.71", "statusTender": "Pasar Dini", "sumberDana": "BUMD JAKPRO", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Info dari pak Wahyu utk KSO rencana dengan JAKON\n- Konsultan Perencana : SURBANA JURONG (Station & System) - Koordinator Utama Konsultan\n                                        CGA (VIADUCT dan CES)\n                                        SAA Arch ( Architecture)\n                                        DARDELA ( Alignment)\n- terinfo dari GM Operasi 2 periode tender akan bergeser ke 2026\n- Survey LIDAR sudah diselesaikan data sudah diberikan ke tim tender", "status": "open"},
  {"id": "52", "keyStatus": "", "name": "Proyek LRT Jakarta Phase 2A : Kelapa Gading - JIS", "operasi": "Operasi 1", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "PT Jakpro", "nilaiOkHps": "1051.05", "statusTender": "Pasar Dini", "sumberDana": "BUMD JAKPRO", "payment": "", "jenisKontrak": "", "periode": "2026-03-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Info dari pak Wahyu utk KSO rencana dengan JAKON\n- Konsultan Perencana : SURBANA JURONG (Station & System) - Koordinator Utama Konsultan\n                                        CGA (VIADUCT dan CES)\n                                        SAA Arch ( Architecture)\n                                        DARDELA ( Alignment)\n- terinfo dari GM Operasi 2 periode tender akan bergeser ke 2026\n- Survey LIDAR sudah diselesaikan data sudah diberikan ke tim tender", "status": "open"},
  {"id": "53", "keyStatus": "", "name": "MRT East - West (CP - 109) - Depot", "operasi": "Operasi 1", "kam": "Dedeng Jefri Arthur", "ktt": "Almadani Jayadi", "owner": "MRT Jakarta", "nilaiOkHps": "3500", "statusTender": "Pasar Dini - RKAP", "sumberDana": "JICA", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- MoU dengan KAJIMA masih berlaku sd 2026, KAJIMA masih menunggu kelanjutan proses merger WIKA oleh danantara khususnya terkait lapkeuangan yang akan diterbitkan\n- Pendanaan JICA\n- Kemungkinan Kontrak 2026\n- diskusi market sounding 29 sept 2025\n- Biweekly dg Kajima dan HK setiap Rabu\n- Kandidat Supplier Depo Equipment mulai dishare oleh KAjima utk direview oleh member Hk dan WIKA", "status": "open"},
  {"id": "54", "keyStatus": "", "name": "MRT East - West (CP 105)", "operasi": "Operasi 1", "kam": "Dedeng Jefri Arthur", "ktt": "Almadani Jayadi", "owner": "MRT Jakarta", "nilaiOkHps": "3000", "statusTender": "Pasar Dini", "sumberDana": "JICA", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Obayashi sudah mau menjadi leadernya WIKA\n- Pendanaan JICA\n- Kemungkinan Kontrak 2026\n- diskusi market sounding 29 sept 2025\n- Obayashi, Jalur Senen-Galur UG", "status": "open"},
  {"id": "55", "keyStatus": "", "name": "MRT East - West (CP 102-103)", "operasi": "Operasi 1", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "MRT Jakarta", "nilaiOkHps": "", "statusTender": "Pasar Dini", "sumberDana": "JICA", "payment": "", "jenisKontrak": "", "periode": "2026-12-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Taisei sudah mau menjadi leadernya WIKA, menunggu hasil koordinasi jepang2\n- Pendanaan JICA\n- Kemungkinan Kontrak 2026\n- diskusi market sounding 29 sept 2025\n- Taisei, jalur UG", "status": "open"},
  {"id": "56", "keyStatus": "", "name": "CP100 : Jakarta Metropolitan MRT East West Line Project Phase 1 Stage 1", "operasi": "Operasi 1", "kam": "Dedeng Jefri Arthur", "ktt": "Almadani Jayadi", "owner": "MRT Jakarta", "nilaiOkHps": "150,00", "statusTender": "Tender Diikuti", "sumberDana": "PT. MRT- J", "payment": "Bulanan", "jenisKontrak": "Gabungan Lumpsum & Unit price", "periode": "2026-01-01", "periodeTender": "Jan-Mar 2026", "pemasukanHarga": "2026-03-31", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Aanwijzing 2 Feb 2026\n- Pemeasukan penawaran tgl 30 Maret 2026", "status": "open"},
  {"id": "57", "keyStatus": "", "name": "Fasilitas Darat KaliBaru", "operasi": "Operasi 1", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "Pelindo", "nilaiOkHps": "400", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- akan JO sama HK", "status": "open"},
  {"id": "58", "keyStatus": "", "name": "Pedestrian Deck Dukuh Atas", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "ITJ", "nilaiOkHps": "240", "statusTender": "Pasar Dini", "sumberDana": "ITJ", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "59", "keyStatus": "", "name": "Perlintasan Simpang Tidak Sebidang Telaga Harapan (Metland)", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "Yasir", "owner": "PT Fajar Putra Dinasti", "nilaiOkHps": "170", "statusTender": "Pasar Dini", "sumberDana": "Swasta PT Metland -", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Peserta: WIKA-Witon, WSKT, Jakon, Modern (to be confirm)\n- Proses pemilihan Konsultan MK oleh Owner, sedang pengajuan NR 1, draft tim tender akan di floor kan\n- Pengguna Jasa bukan Metland, tapi anak usahanya (FAJAR PUTRA DINASTI)\n- Terinfo saat ini (9 Sept 2025) pengadaan lahan  keseluruhan, tender akan mulai di proses ketika lahan sudah diadakan keseluruhannya\n- NR 1 sudah diajukan", "status": "open"},
  {"id": "60", "keyStatus": "", "name": "On Off Ramp Nanjung - Tol SOROJA", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "", "owner": "CMLP", "nilaiOkHps": "150", "statusTender": "Pasar Dini", "sumberDana": "Swasta CMLP", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Tim QS akan menghitung BoQ setelah desain ada\n- Tim Lidar sudah survey LiDar hari senin 4 Agustus 2025\n- Sudah diberikan data kontur kepada KTT dari tim LIDAR\n- Ada kendala pembebasan lahan On Off Ramp nya, sehingga proyek akan di postpone ke Tahun 2026 hingga waktu yang akan diinfokan kembali oleh Owner.", "status": "open"},
  {"id": "61", "keyStatus": "", "name": "Patimban Port Paket 7A", "operasi": "Operasi 1", "kam": "Fajar Ariyanto", "ktt": "", "owner": "Kemenhub", "nilaiOkHps": "450", "statusTender": "Pasar Dini - RKAP", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-07-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Proses RBP di Owner", "status": "open"},
  {"id": "62", "keyStatus": "", "name": "Eco Fishing  Cilacap (Tambak)", "operasi": "Operasi 1", "kam": "Fajar Ariyanto", "ktt": "", "owner": "KKP", "nilaiOkHps": "350", "statusTender": "", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "-Info KAM PQ Oktober 2025", "status": "open"},
  {"id": "63", "keyStatus": "", "name": "Jalan Tol JOR Eleveted Ulujami Cikunir", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "MUN", "nilaiOkHps": "1500", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Info dari KAM dari rencana rekanan sudah lama tidak kelihatan", "status": "open"},
  {"id": "64", "keyStatus": "", "name": "Pelebaran Jalan Tol Cirebon", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "", "owner": "PT. Jasa Marga", "nilaiOkHps": "200", "statusTender": "", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "65", "keyStatus": "Cancel", "name": "Akses Tol Patimban", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "", "owner": "PT. Jasa Marga", "nilaiOkHps": "250", "statusTender": "", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-03-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Close", "statusSaatIni": "- Info dari KAM ini adalah paket 2 yang telah didapatkan tetap masuk RKAP 2026 karena disusun dan disahkan sebelum desember 2026, untuk akses patimban paket 2 didapatkan di desember 2026", "status": "closed"},
  {"id": "66", "keyStatus": "", "name": "Rest Area Cisumdawu", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "", "owner": "CKJT", "nilaiOkHps": "250", "statusTender": "Pasar Dini", "sumberDana": "Swasta CKJT", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "67", "keyStatus": "", "name": "Fly Over Klaten-1", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "Dendy P", "owner": "PU-Bina Marga", "nilaiOkHps": "180", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "-Info KAM sudah RPB kemungkinan tayang belum tahun ini", "status": "open"},
  {"id": "68", "keyStatus": "", "name": "Fly Over Klaten-2", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "Dendy P", "owner": "PU-Bina Marga", "nilaiOkHps": "200", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "-Info KAM sudah RPB kemungkinan tayang belum tahun ini", "status": "open"},
  {"id": "69", "keyStatus": "", "name": "BRT Jalur On Corridor Semarang", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "", "owner": "Kemenhub", "nilaiOkHps": "300", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-05-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "70", "keyStatus": "", "name": "Tol Bawen Jogja", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "R.Rizki J", "owner": "PT. Jasa Marga", "nilaiOkHps": "400", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "71", "keyStatus": "", "name": "Jembatan Kali Bedadung - Pansela (Jatim)", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "R.Rizki J", "owner": "PU - Bina Marga", "nilaiOkHps": "200", "statusTender": "Pasar Dini - RKAP", "sumberDana": "Loan ADB", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM akan luncur 6 paket sekaligus di April 2026, PQ, Loan ADB", "status": "open"},
  {"id": "72", "keyStatus": "", "name": "Jalan Pansela Ruas Puger-Senen", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "R.Rizki J", "owner": "PU - Bina Marga", "nilaiOkHps": "", "statusTender": "Pasar Dini", "sumberDana": "Loan ADB", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM akan luncur 6 paket sekaligus di Oktober 2025, PQ, Loan ADB\n- Sasaran Utama \n- Member, leader nya HK", "status": "open"},
  {"id": "73", "keyStatus": "", "name": "Pembangunan Jalan Senen Rejo - Banyuwangi 3", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "R.Rizki J", "owner": "PU - Bina Marga", "nilaiOkHps": "230", "statusTender": "Pasar Dini", "sumberDana": "Loan ADB", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Info KAM akan luncur 6 paket sekaligus di Oktober 2025, PQ, Loan ADB\n- Sasaran Utama \n- KSO, wika leader", "status": "open"},
  {"id": "74", "keyStatus": "", "name": "Temporary Runway Bandara Juanda Surabaya", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "Dendy P", "owner": "ANGKASA PURA", "nilaiOkHps": "800", "statusTender": "Pasar Dini - RKAP", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-06-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "- Akan KSO dengan NK, slow respon\n- Tender akan dilaksanakan 2026", "status": "open"},
  {"id": "75", "keyStatus": "", "name": "Fly Over Pelangi", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "Rivai", "owner": "PU-Bina Marga", "nilaiOkHps": "300", "statusTender": "Pasar Dini", "sumberDana": "APBN", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "-'Info KAM belum RPB", "status": "open"},
  {"id": "76", "keyStatus": "", "name": "Be Handle Tanjung Priok", "operasi": "Operasi 1", "kam": "Dedeng Jefri Arthur", "ktt": "M. Andri / Edy Suyanto", "owner": "Pelindo", "nilaiOkHps": "250", "statusTender": "", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "77", "keyStatus": "Submit", "name": "Jalan Ringinrejo - Sp. Jolosutro", "operasi": "Operasi 2", "kam": "Fajar Ariyanto", "ktt": "Rizki J", "owner": "PU-Bina Marga", "nilaiOkHps": "463", "statusTender": "Tender Diikuti", "sumberDana": "IsDB", "payment": "Termijn min 1%", "jenisKontrak": "Unit price", "periode": "2026-02-01", "periodeTender": "Feb-Mar 2026", "pemasukanHarga": "2026-03-12", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "_Rencana pemasukan penawan 13 Maret 2026\n- Isue qualifikasi keuangan dan pengalaman pekerjaan soil nailing dan rumput templok msh jadi kendala pemenuhannya\n- target submit 13 Maret 2026", "status": "open"},
  {"id": "78", "keyStatus": "Submit", "name": "Tanggul Muara Karang", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "Ridwan Budi", "owner": "APL", "nilaiOkHps": "", "statusTender": "Budgetary", "sumberDana": "APL", "payment": "", "jenisKontrak": "", "periode": "2026-02-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "79", "keyStatus": "Submit", "name": "Off Ramp Bocimi", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "Dody Arief", "owner": "Sinarmas", "nilaiOkHps": "", "statusTender": "Budgetary", "sumberDana": "Sinarmas", "payment": "", "jenisKontrak": "", "periode": "2026-03-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "80", "keyStatus": "", "name": "Tol Solo - Jogja Ruas ke Bandara NYIA", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "Dendy P", "owner": "", "nilaiOkHps": "", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "81", "keyStatus": "", "name": "Tol Serang Panimbang Seksi 3B Lanjutan", "operasi": "Operasi 2", "kam": "Dedeng Jefri Arthur", "ktt": "Edy Suyanto", "owner": "", "nilaiOkHps": "", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Ehan Rohandi", "koordinatorStatus": "Active", "statusSaatIni": "", "status": "open"},
  {"id": "82", "keyStatus": "", "name": "Container Yard BMS (Berlian Manyar Sejahtera)", "operasi": "Operasi 1", "kam": "Dedeng Jefri Arthur", "ktt": "Dendy P", "owner": "Pelindo", "nilaiOkHps": "250", "statusTender": "Pasar Dini", "sumberDana": "", "payment": "", "jenisKontrak": "", "periode": "2026-04-01", "periodeTender": "", "pemasukanHarga": "", "koordinatorQs": "Budi Raharjo", "koordinatorStatus": "Active", "statusSaatIni": "-'Info KAM belum RPB", "status": "open"},
];

export function formatDate(iso: string) {
  if (!iso) return "-";
  return new Date(iso).toLocaleDateString("id-ID", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

export function formatPeriode(iso: string) {
  if (!iso) return "-";
  return new Date(iso).toLocaleDateString("id-ID", {
    month: "long",
    year: "numeric",
  });
}

export function formatNilai(v: string) {
  if (!v) return "-";
  const n = Number(v);
  return Number.isFinite(n) ? `${n.toLocaleString("id-ID")} M` : v;
}
